data: add header v2 and interfaces
ElrondNetwork/elrond-go-core pull request #2
Opened 2021-07-21 08:12 UTC by AdoAdoAdo

2021-07-21 09:11 UTC, SebastianMarian approved these changes

2021-07-23 09:33 UTC, bogdan-rosianu requested changes

2021-07-23 09:33 UTC, bogdan-rosianu commented on go.mod
> +	github.com/shirou/gopsutil v0.0.0-20190901111213-e4ec7b275ada // indirect
remove this dep and run `go mod vendor` and `go mo tidy` again

2021-07-23 14:00 UTC, SebastianMarian submitted a review, later dismissed

2021-08-09 06:35 UTC, SebastianMarian submitted a review, later dismissed

2022-01-31 14:42 UTC, iulianpascalau approved these changes

2022-01-31 14:42 UTC, bogdan-rosianu approved these changes

2022-01-31 14:43 UTC, merged