receipts in mb
ElrondNetwork/elrond-go-core pull request #62
Opened 2022-01-20 12:09 UTC by miiu96

2022-02-08 08:14 UTC, iulianpascalau approved these changes

2022-02-08 08:22 UTC, bogdan-rosianu requested changes

2022-02-09 12:25 UTC, miiu96 commented on data/api/apiBlock.go
> +	Receipts         []*transaction.ApiReceipt           `json:"receipt,omitempty"`
done./

2022-02-09 12:46 UTC, iulianpascalau approved these changes

2022-02-09 13:27 UTC, bogdan-rosianu approved these changes

2022-02-09 14:35 UTC, merged